<template>
    <default-field :field="field">
        <template slot="field">
            <loading-view :loading="deleting">
                <div class="picker-wrapper">
                    <PicturePicker
                        :aspect-ratio="field.aspectRatio"
                        @deleteImage="confirmRemoval"
                        @fileChanged="setFile"
                        @thumbFileChanged="setThumbFile"
                        ref="picturePicker"
                        v-model="value"
                        v-show="editingImage || !value"
                    />
                    <p
                        class="my-2 text-danger"
                        v-if="hasError"
                    >{{ firstError }}</p>

                    <portal to="modals">
                        <transition name="fade">
                            <confirm-upload-removal-modal
                                @close="closeRemoveModal"
                                @confirm="removeFile"
                                v-if="removeModalOpen"
                            />
                        </transition>
                    </portal>
                </div>
            </loading-view>
        </template>
    </default-field>
</template>

<script>
	import {Errors, FormField, HandlesValidationErrors} from 'laravel-nova'
	import PicturePicker from './PicturePicker'

	require('element-ui/lib/theme-chalk/index.css');

	export default {
		components: {PicturePicker},

		mixins: [FormField, HandlesValidationErrors],

		props: ['resourceName', 'resourceId', 'field'],

		data() {
			return {
				deleting: false,
				editingImage: false,
				thumbFile: null,
				file: null,
				origFile: null,
				fileName: '',
				removeModalOpen: false,
				uploadErrors: new Errors()
			}
		},

		computed: {
			/**
			 * Determine whether the field should show the remove button
			 */
			shouldShowRemoveButton() {
				return Boolean(this.field.deletable)
			},

			/**
			 * Determine if should hit the endpoint for delete
			 */
			imageExistsOnServer() {
				return Boolean(this.field.previewUrl)
			}
		},

		mounted() {
			this.value = this.field.previewUrl;
			this.field.fill = formData => {
				if (this.file) {
					formData.append(this.field.attribute, this.file, this.fileName)
				}
			}
		},

		methods: {
			/*
             * Set the initial, internal value for the field.
             */
			setInitialValue() {
				this.value = this.field.value || ''
			},

			/*
             * Set the file generated by the cropper.
             */
			setFile(file) {
				this.editingImage = true;
				// console.log('setFile');
				this.file = file;
				this.fileName = file.name
			},
			setThumbFile(file) {
				// console.log('setThumbFile');
				this.thumbFile = file
			},

			/*
             * Reset the file state.
             */
			resetFile(file) {
				this.file = null;
				this.thumbFile = null;
				this.fileName = '';
				this.value = ''
			},

			/**
			 * Confirm removal of the linked file
			 */
			confirmRemoval() {
				// this.editingImage = false
				this.removeModalOpen = true
			},

			/**
			 * Close the upload removal modal
			 */
			closeRemoveModal() {
				this.removeModalOpen = false
				// this.editingImage = true
			},

			/**
			 * Remove the linked file from storage
			 */
			async removeFile() {
				this.closeRemoveModal();

				if (!this.imageExistsOnServer) {
					this.resetFile();
					return
				}

				this.deleting = true;
				this.uploadErrors = new Errors();

				const {
					resourceName,
					resourceId,
					relatedResourceName,
					relatedResourceId,
					viaRelationship
				} = this;
				const attribute = this.field.attribute;

				const uri = this.viaRelationship
					? `/nova-api/${resourceName}/${resourceId}/${relatedResourceName}/${relatedResourceId}/field/${attribute}?viaRelationship=${viaRelationship}`
					: `/nova-api/${resourceName}/${resourceId}/field/${attribute}`;

				try {
					await Nova.request().delete(uri);
					this.deleting = false;
					this.resetFile();
					this.$emit('file-deleted')
				} catch (error) {
					this.deleting = false;

					if (error.response.status == 422) {
						this.uploadErrors = new Errors(error.response.data.errors)
					}
				}
			},

			/**
			 * Update the field's internal value.
			 */
			handleChange(value) {
				// console.log('handleChange');
				this.value = value
			}
		}
	}
</script>
<style scoped>
</style>
